# Site settings
title: Esther Ling
email: lingesther@gatech.edu
description: > # this means to ignore newlines until "baseurl:"
  Machine Learning / Computer Vision engineer
baseurl:  # the subpath of your site, e.g. /blog/
url: "https://lefthandwriter.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  lefthandwriter

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  # poetry:
  #   output: true
  #   permalink: /poetry/:path/


